# .github/workflows/d1-insights-to-r2.yml
name: Daily D1 Insights → R2
on:
  schedule:
    - cron: '15 0 * * *'   # UTC 00:15 = 한국 09:15
  workflow_dispatch:

jobs:
  export_and_upload:
    runs-on: ubuntu-latest
    env:
      # 기존 Secrets
      CF_API_TOKEN:    ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID:   ${{ secrets.CF_ACCOUNT_ID }}

      # Wrangler용 새 이름
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }} 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      D1_DB_NAME: ${{ secrets.D1_DB_NAME }}

    steps:
      - name: Install Wrangler
        run: npm i -g wrangler@latest

      - name: Export last-31 days insights
        run: |
          set -euo pipefail
          TODAY=$(date -u '+%Y-%m-%d')

          npx -y wrangler@latest d1 insights "$D1_DB_NAME" \
            --json --timePeriod=31d \
            > "insights_${TODAY}.json"

       # 3. S3 업로드(동기화)
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --exact-timestamps
