# .github/workflows/d1-insights-to-r2.yml
name: Daily D1 Insights → R2
on:
  schedule:
    - cron: '15 0 * * *'   # UTC 00:15 = 한국 09:15
  workflow_dispatch:

jobs:
  export_and_upload:
    runs-on: ubuntu-latest
    env:
      # 기존 Secrets
      CF_API_TOKEN:    ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID:   ${{ secrets.CF_ACCOUNT_ID }}

      # Wrangler용 새 이름
      CLOUDFLARE_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      D1_DB_NAME: ${{ secrets.D1_DB_NAME }}

    steps:
      - name: Install Wrangler
        run: npm i -g wrangler@latest

      - name: Export last-31 days insights
        run: |
          set -euo pipefail
          TODAY=$(date -u '+%Y-%m-%d')

          npx -y wrangler@latest d1 insights "$D1_DB_NAME" \
            --json --timePeriod=31d \
            > "insights_${TODAY}.json"

      - name: Upload to R2
        uses: ryand56/r2-upload-action@v1.4
        with:
          r2-account-id:        ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id:     ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket:            ${{ secrets.R2_BUCKET }}
          source-dir:           '.'
          destination-dir:      'd1-insights/'
